apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  namespace: petclinic
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: caannamalai/config-server:3.2.4
          ports:
            - containerPort: 8888
---

apiVersion: v1
kind: Service
metadata:
  name: configserver-service
  namespace: petclinic
  labels:
    app: configserver
spec:
  selector:
    app: configserver
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: configserver-ingress
  namespace: petclinic
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ""
      http:
        paths:
          - path: /configserver
            pathType: Prefix
            backend:
              service:
                name: configserver-service
                port:
                  number: 8888
