# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-creator-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: sample@***.iam.gserviceaccount.com
  namespace: default
roleRef:
  kind: Role
  name: sample@***.iam.gserviceaccount.com
  apiGroup: rbac.authorization.k8s.io
